[flavor]
dark = "rose-pine"

[app]
overall = { bg = "reset" }

[mode]
normal_main = { fg = "#191724", bg = "#ebbcba", bold = true }
normal_alt  = { fg = "#e0def4", bg = "#26233a" }

select_main = { fg = "#191724", bg = "#c4a7e7", bold = true }
select_alt  = { fg = "#e0def4", bg = "#26233a" }

unset_main = { fg = "#191724", bg = "#eb6f92", bold = true }
unset_alt  = { fg = "#e0def4", bg = "#26233a" }

[status]
overall = { fg = "#e0def4", bg = "reset" }
