set -ga terminal-overrides ",tmux-256color*:Tc" 
# set -ga terminal-overrides ",tmux-ghostty*:Tc" 
set-option -g default-terminal "tmux-256color"
# set-option -g default-terminal "tmux-ghostty"
set -s escape-time 0
set -g assume-paste-time 0
set -g status off
set -g mouse on

set -g status-style 'bg=default,fg=#31748f'

set -g window-status-current-format '(#W)'
set -g window-status-format ' #W '

set -g status-right-length 100
set -g status-left-length 100
set -g status-right '#{pane_current_path}'
set -g status-left '[#S] '

unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

bind -n M-H previous-window
bind -n M-L next-window

bind r source-file ~/.config/tmux/tmux.conf

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind-key -r f run-shell "tmux neww ~/.local/bin/tmux-sessionizer"

bind-key -r H run-shell "~/.local/bin/tmux-sessionizer ~/prog/money_manager"
bind-key -r T run-shell "~/.local/bin/tmux-sessionizer ~/prog/drone/code"
bind-key -r N run-shell "~/.local/bin/tmux-sessionizer ~/prog/zigcraft"
bind-key -r S run-shell "~/.local/bin/tmux-sessionizer ~/descriptor_vs_graph_based_models"

bind-key -r t set -g status

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind-key -r C-h select-pane -L
bind-key -r C-j select-pane -D
bind-key -r C-k select-pane -U
bind-key -r C-l select-pane -R

run '~/.config/tmux/plugins/tpm/tpm'
